name: CI/CD Pipeline

# 트리거: main 브랜치에 push될 때 또는 pull request가 있을 때 작동
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Docker 버전 확인 (디버깅용)
      - name: Set up Docker
        run: docker --version

      # 3. Docker 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. 애플리케이션 빌드 (Gradle)
      - name: Build application with Gradle
        run: ./gradlew build -x test

      # 5. Docker 이미지 빌드
      - name: Build Docker image
        run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/backend:latest

      # 6. Docker 이미지 푸시
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # 1. EC2 서버에 SSH로 접근하여 Docker 컨테이너 업데이트
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/backend:latest
            docker stop backend || true
            docker rm backend || true
            docker run -d -p 8080:8080 --name backend ${{ secrets.DOCKER_USERNAME }}/backend:latest
